#
# (C) Copyright 2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

#obj-$(CONFIG_MCU_UART2IIC) += mcu_u2i.o
#mcu_u2i-objs := mcu_uart.o to_i2c.o

obj-y += libsecret.o

libsecret-objs :=  SecretMain.o \
                     SecretIC.o \
                     SHA204.o \
                     SHA204_comm.o \
                     SHA256.o \
                     Host_Cal.o \
                     I2C_phys.o

